### ISSUE TITLE
Call notification disappears when Google play is running

### ISSUE THREAD

**Issue by schuttj** [simlar/simlar-ios#1]
Environment:
Calling from: Nexus 7 
Calling to: iPhone 5 IOS 8.1.1 with Google Play app running 

The display is active and the music plays. The call is a dropdown notification that disappears again. There is only one buzz of the cell phone. 

Expected behavior:
The notification should be more prominent and should not disappear. The cell should be buzzing like with normal calls.

**Comment by jritzerfeld** [comment]
Pullrequest #57 introduced more than one buzz on incoming calls.

**Comment by jritzerfeld** [comment]
Fixed in release 0.0.8.
