### ISSUE TITLE
Directly calling s.o. after account creation fails

### ISSUE THREAD

**Issue by BenSartor** [simlar/simlar-ios#130]
Reproduction
* delete app
* install app again and create an account
* try calling s.o.
* Alert appears: "iOS blocked call ..."
![bug-first-call-after-account-creation](https://user-images.githubusercontent.com/1279973/90837743-33425f80-e353-11ea-8376-648914a44018.png)

**Comment by DennisKlipp** [comment]
Thank you for fixing!

**Comment by BenSartor** [comment]
Hi @DennisKlipp,

thanks for commenting this issue!

Actually we can close it once pullrequest #133 is merged and we have new version in the app store.

Cheers,
 Ben
