### ISSUE TITLE
iPhone 5, iOS 8.11 Ring tone played by internal Speaker

### ISSUE THREAD

**Issue by BastianKX** [simlar/simlar-ios#25]
Ring tone is played by the internal speaker and so is very quit. Think it should be played on the external one.

iPhone 5, iOS 8.11

**Comment by jritzerfeld** [comment]
@BastianKX Does this problem still exist for you?

**Comment by jritzerfeld** [comment]
No response, closing, feel free to reopen if problem still exists.
