### ISSUE TITLE
misplaced="YES" in Simlar/Base.lproj/Main.storyboard

### ISSUE THREAD

**Issue by jritzerfeld** [simlar/simlar-ios#47]
By updating to XCode 7.3 there were added many 'misplaced="YES"' to Simlar/Base.lproj/Main.storyboard
This might explain it: [Misplaced views each time Xcode restarts](http://stackoverflow.com/questions/29289892/misplaced-views-each-time-xcode-restarts)

**Comment by MyraBaba** [comment]
Hi,

When I run the code in the Xcode I have below error after submitting number n the simultor. 

Any idea..?

thx


![error](https://cloud.githubusercontent.com/assets/17505439/20404933/008f0112-ad18-11e6-8ddd-4fc96d96a2e9.png)
![error](https://cloud.githubusercontent.com/assets/17505439/20404943/0e70b640-ad18-11e6-98b1-034c73993435.png)

**Comment by BenSartor** [comment]
fixed meanwhile
