### ISSUE TITLE
Force-quitted Simlar gets killed after 30 seconds of ringing

### ISSUE THREAD

**Issue by jritzerfeld** [simlar/simlar-ios#54]
If the user force-quits the Simlar app and gets called, iOS 9 will kill the app after about 30 seconds of ringing. But the caller still thinks it is ringing and does not hang up automatically. So, if the callee immediately calls back he will get "Busy".

iOS 6 limited such a background task to 600 seconds, iOS 7 and 8 to 180 seconds, and iOS 9 to 30 seconds. The Simlar app has to check the remaining time in its expiration handler and to hang up and and end the background task when the time is running out.

Effectively, ringing is limited to 30 seconds then. However, if the Simlar app is in foreground, the limit set by iOS is much higher and the Simlar app is able to ring much longer.

**Comment by BenSartor** [comment]
Hi @jritzerfeld,

thanks for your Bug-Report. This issue was fixed in pullrequest #49. We should close it once we 
manage to get the next release in the app store.

**Comment by jritzerfeld** [comment]
Fixed in release 0.0.8.
